"""SpeedChatGlobals.py: global SpeedChat data """

# If you just want to know when a speedchat message is selected,
# see the events in ChatManager.py.

# These are the base names of the events that may be generated by
# a SpeedChat object.
# To get the actual event name, use:
# speedChat.getEventName(eventBaseName)
# where 'speedChat' is your SpeedChat object, and 'eventBaseName' is
# one of the following:
from SCTerminal           import SCTerminalSelectedEvent
from SCTerminal           import SCTerminalLinkedEmoteEvent
from SCStaticTextTerminal import SCStaticTextMsgEvent
from SCGMTextTerminal import SCGMTextMsgEvent
from SCCustomTerminal     import SCCustomMsgEvent
from SCEmoteTerminal      import SCEmoteMsgEvent, SCEmoteNoAccessEvent

# SCColorSchemeChangeMsgEvent

# See the individual SC*Terminal.py files for documentation of the
# arguments included with each message.
