"""TTSpeedChatGlobals.py: global Toontown specific SpeedChat data """

# These are the base names of the events that may be generated by
# a SpeedChat object.
# To get the actual event name, use:
# speedChat.getEventName(eventBaseName)
# where 'speedChat' is your SpeedChat object, and 'eventBaseName' is
# one of the following:
from TTSCToontaskTerminal   import TTSCToontaskMsgEvent
from TTSCResistanceTerminal   import TTSCResistanceMsgEvent
