#! /bin/sh

if [ "$1" = "-d" ]
then
    destdir=$2
    debug_state="-d"
else
    destdir=$1
    debug_state=""
fi

if [ "${destdir}" = "" ]
then
	echo "Usage: AIcopyfiles [-d] destdir"
	exit 1
fi

if [ ! -d ${destdir} ]
then
	echo "Error: destdir must be a directory"
	exit 1
fi

for file in `AIprintfiles $debug_state`
do
	copyTo=${destdir}

        moduleDir=`dirname ${file}`
	srcDir=`dirname ${moduleDir}`
        packageDir=`dirname ${srcDir}`

        # check to see there is sub pkg dir

        if [ `basename ${packageDir}` != src ]; then

             # subdir doesn't exist, proceed as before

             moduleDir=`basename ${moduleDir}`
             srcDir=`basename ${srcDir}`
             packageDir=`basename ${packageDir}`

        else

             # subdir exists, need to use extra variable and
             # create new moduleDir 

             moduleSubDir=${moduleDir}
             moduleDir=`dirname ${moduleSubDir}`
             srcDir=`dirname ${moduleDir}`
             packageDir=`dirname ${srcDir}`

             moduleDir=`basename ${moduleDir}`/`basename ${moduleSubDir}`
             srcDir=`basename ${srcDir}`
             packageDir=`basename ${packageDir}`
        fi

        
        if [ `basename ${file} .py` != `basename ${file}` ]; then
            # The file is a Python file.  Is it in a src directory?
            if [ ${srcDir} = src ]; then
		copyPkg=${destdir}/${packageDir}
                copyTo=${copyPkg}/${moduleDir}
                (mkdir ${copyPkg}; touch ${copyPkg}/__init__.py) > /dev/null 2>&1
                (mkdir ${copyTo}; touch ${copyTo}/__init__.py) > /dev/null 2>&1
	    elif [ ${moduleDir} = pandac ]; then
                copyTo=${destdir}/pandac
                (mkdir ${copyTo}; touch ${copyTo}/__init__.py) > /dev/null 2>&1
            fi
        fi

	if cp ${file} ${copyTo}
	then
	    echo "copying ${file} to ${copyTo}"
	else
	    echo "ERROR: could not find ${file}"
	    exit 1
	fi
done
