
// This file was generated by make-prc-key.  It can be compiled against
// dtool to produce a program that will sign a prc file using key number 1.

static const char * const prc_privkey1_data =
  "-----BEGIN PRIVATE KEY-----\n"
  "MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBANibE+jSnO7weH61\n"
  "4enud4xnLQYlAyoRn892P/bp5VPINcvtiSctufVCkOPKG/Y/JBxcxxSgtMQD2Tuj\n"
  "ex1EpY0W0P17185wiPhmaEieWUimQMha3WGaxEVkIefMb6J771GrbF+xNOgiq9fd\n"
  "i7zwE21U19jaJ6U9DMpOwCtlYjCRAgEHAoGAHvGVIUKotGt+7YeyjyIRFA69SgVJ\n"
  "mEupHaMttY8gwtN1ZkaBTr1jtVKm+/hNIy2XccQccKk+ZSUfCIURlneFXQkewsnl\n"
  "GW1accPvXId70rImuYJ06oBAGNeNu4aIdc6DuebbvQtzolSX+XdeoapnWyLNFSpQ\n"
  "1Fcxe62qObnJpXcCQQDtUPJken0nsa7zyqHNDcAy2eE8wHiuw0reR0dxSUOSWBAs\n"
  "VXfujTVt5SDgaCf8PgKMM8SswayKoITrz3S9MFVpAkEA6ai3khmfS14tFxIfHOjF\n"
  "lFfUjOp/akBMoPp/rWsmQ/0sLxS8cn5CZJ7kuY0pSwHs1QiABTAqUBHjo0kik65U\n"
  "6QJBAIeb+DlqkKj30a/hgQd1kmYzXCK3IGPdT1px365zAgp7dvTDH/YHjD7MEslg\n"
  "FtlIAXSv3hmTPgYSlRkI1P5kwxcCQQCm5jn6pJZaZ9cQeqiCXR9p9ZfSXlsCwDa8\n"
  "IKRXTIkL/fr9Ds+/fsG1lhEW0os1k6kqc8koRvmm6DTiWM+ODs7vAkEA201TVcJ2\n"
  "rJEaZe0LhkGYCZyvRTvO/Oex4u16jG6aQIu0QxLOCYj2sJ5eJxpo47NXQt87hDiY\n"
  "Ucs62YGXHpcEog==\n"
  "-----END PRIVATE KEY-----\n";
static const unsigned int prc_privkey1_length = 916;


#define KEY_NUMBER 1
#define KEY_DATA prc_privkey1_data
#define KEY_LENGTH prc_privkey1_length
#define PROGNAME "otp_sign1"
#define GENERATED_TIME 1190315171

#include "signPrcFile_src.cxx"

