
// This file was generated by make-prc-key.  It defines the public keys
// that will be used to validate signed prc files.

#include "prcKeyRegistry.h"

static const char * const prc_pubkey1_data =
  "-----BEGIN PUBLIC KEY-----\n"
  "MIGdMA0GCSqGSIb3DQEBAQUAA4GLADCBhwKBgQDYmxPo0pzu8Hh+teHp7neMZy0G\n"
  "JQMqEZ/Pdj/26eVTyDXL7YknLbn1QpDjyhv2PyQcXMcUoLTEA9k7o3sdRKWNFtD9\n"
  "e9fOcIj4ZmhInllIpkDIWt1hmsRFZCHnzG+ie+9Rq2xfsTToIqvX3Yu88BNtVNfY\n"
  "2ielPQzKTsArZWIwkQIBBw==\n"
  "-----END PUBLIC KEY-----\n";
static const unsigned int prc_pubkey1_length = 272;

static PrcKeyRegistry::KeyDef const prc_pubkeys[2] = {
  { NULL, 0, 0 },
  { prc_pubkey1_data, prc_pubkey1_length, 1190315171 },
};
static const int num_prc_pubkeys = 2;

