from toontown.coghq.SpecImports import *

GlobalEntities = {
    # LEVELMGR
    1000: {
        'type': 'levelMgr',
        'name': 'LevelMgr',
        'comment': '',
        'parentEntId': 0,
        'cogLevel': 0,
        'farPlaneDistance': 1500,
        'modelFilename': 'phase_11/models/lawbotHQ/LB_Zone08a',
        'wantDoors': 1,
        }, # end entity 1000
    # EDITMGR
    1001: {
        'type': 'editMgr',
        'name': 'EditMgr',
        'parentEntId': 0,
        'insertEntity': None,
        'removeEntity': None,
        'requestNewEntity': None,
        'requestSave': None,
        }, # end entity 1001
    # ZONE
    0: {
        'type': 'zone',
        'name': 'UberZone',
        'comment': '',
        'parentEntId': 0,
        'scale': 1,
        'description': '',
        'visibility': [],
        }, # end entity 0
    # ATTRIBMODIFIER
    10010: {
        'type': 'attribModifier',
        'name': 'goonStrength',
        'comment': '',
        'parentEntId': 100021,
        'attribName': 'strength',
        'recursive': 1,
        'typeName': 'goon',
        'value': '15',
        }, # end entity 10010
    # COLLISIONSOLID
    10015: {
        'type': 'collisionSolid',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10007,
        'pos': Point3(0, 2, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'length': 3.0,
        'radius': 3.0,
        'showSolid': 0,
        'solidType': 'tube',
        }, # end entity 10015
    10017: {
        'type': 'collisionSolid',
        'name': 'copy of <unnamed>',
        'comment': '',
        'parentEntId': 10018,
        'pos': Point3(0, 2, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'length': 3.0,
        'radius': 3.0,
        'showSolid': 0,
        'solidType': 'tube',
        }, # end entity 10017
    10026: {
        'type': 'collisionSolid',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10024,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'length': 3.0,
        'radius': 1.0,
        'showSolid': 0,
        'solidType': 'tube',
        }, # end entity 10026
    10027: {
        'type': 'collisionSolid',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10023,
        'pos': Point3(51.033, -2.36694, -0.821283),
        'hpr': Vec3(0, 0, 0),
        'scale': Vec3(1, 1, 1),
        'length': 10.0,
        'radius': 7.0,
        'showSolid': 0,
        'solidType': 'tube',
        }, # end entity 10027
    10028: {
        'type': 'collisionSolid',
        'name': 'copy of <unnamed>',
        'comment': '',
        'parentEntId': 10023,
        'pos': Point3(14.9923, 28.704, -0.821283),
        'hpr': Vec3(0, 0, 0),
        'scale': Vec3(1, 1, 1),
        'length': 10.0,
        'radius': 7.5181885051801318,
        'showSolid': 0,
        'solidType': 'tube',
        }, # end entity 10028
    10038: {
        'type': 'collisionSolid',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10035,
        'pos': Point3(-2.32046, 0.439226, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': Vec3(1, 1, 1),
        'length': 6.0,
        'radius': 0.80000000000000004,
        'showSolid': 0,
        'solidType': 'tube',
        }, # end entity 10038
    10041: {
        'type': 'collisionSolid',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10040,
        'pos': Point3(2.4512, 1.72783, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': Vec3(1, 1, 1),
        'length': 10.0,
        'radius': 4.0,
        'showSolid': 0,
        'solidType': 'tube',
        }, # end entity 10041
    # GOON
    10001: {
        'type': 'goon',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10000,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 3.5,
        'attackRadius': 15,
        'crushCellId': None,
        'goonType': 'sg',
        'gridId': None,
        'hFov': 70,
        'strength': 15,
        'velocity': 4,
        }, # end entity 10001
    10008: {
        'type': 'goon',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10003,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 3.5,
        'attackRadius': 15,
        'crushCellId': None,
        'goonType': 'sg',
        'gridId': None,
        'hFov': 70,
        'strength': 15,
        'velocity': 4,
        }, # end entity 10008
    10012: {
        'type': 'goon',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10011,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 3.5,
        'attackRadius': 15,
        'crushCellId': None,
        'goonType': 'sg',
        'gridId': None,
        'hFov': 70,
        'strength': 15,
        'velocity': 4,
        }, # end entity 10012
    10020: {
        'type': 'goon',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10019,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 3.5,
        'attackRadius': 15,
        'crushCellId': None,
        'goonType': 'sg',
        'gridId': None,
        'hFov': 70,
        'strength': 15,
        'velocity': 4,
        }, # end entity 10020
    10047: {
        'type': 'goon',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10046,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 3.5,
        'attackRadius': 15,
        'crushCellId': None,
        'goonType': 'sg',
        'gridId': None,
        'hFov': 70,
        'strength': 15,
        'velocity': 4,
        }, # end entity 10047
    10052: {
        'type': 'goon',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10051,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 3.5,
        'attackRadius': 15,
        'crushCellId': None,
        'goonType': 'sg',
        'gridId': None,
        'hFov': 70,
        'strength': 15,
        'velocity': 4,
        }, # end entity 10052
    10057: {
        'type': 'goon',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10056,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 3.5,
        'attackRadius': 15,
        'crushCellId': None,
        'goonType': 'sg',
        'gridId': None,
        'hFov': 70,
        'strength': 15,
        'velocity': 4,
        }, # end entity 10057
    # MODEL
    10007: {
        'type': 'model',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10009,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(164.055, 0, 0),
        'scale': Vec3(7, 7, 7),
        'collisionsOnly': 0,
        'flattenType': 'light',
        'goonHatType': 'hardhat',
        'loadType': 'loadModelCopy',
        'modelPath': 'phase_9/models/char/Cog_Goonie-zero',
        }, # end entity 10007
    10018: {
        'type': 'model',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10016,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(215, 0, 0),
        'scale': Vec3(7, 7, 7),
        'collisionsOnly': 0,
        'flattenType': 'light',
        'goonHatType': 'hardhat',
        'loadType': 'loadModelCopy',
        'modelPath': 'phase_9/models/char/Cog_Goonie-zero',
        }, # end entity 10018
    10024: {
        'type': 'model',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10025,
        'pos': Point3(39.8396, -3.38811, 2),
        'hpr': Vec3(45, 280, 0),
        'scale': Vec3(10, 10, 10),
        'collisionsOnly': 0,
        'flattenType': 'light',
        'goonHatType': 'hardhat',
        'loadType': 'loadModelCopy',
        'modelPath': 'phase_9/models/char/Cog_Goonie-zero',
        }, # end entity 10024
    10031: {
        'type': 'model',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10037,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'collisionsOnly': 0,
        'flattenType': 'light',
        'goonHatType': 'none',
        'loadType': 'loadModelCopy',
        'modelPath': 'phase_11/models/lawbotHQ/LB_filing_cabA.bam',
        }, # end entity 10031
    10032: {
        'type': 'model',
        'name': 'copy of <unnamed>',
        'comment': '',
        'parentEntId': 10037,
        'pos': Point3(1.75, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'collisionsOnly': 0,
        'flattenType': 'light',
        'goonHatType': 'none',
        'loadType': 'loadModelCopy',
        'modelPath': 'phase_11/models/lawbotHQ/LB_filing_cabA.bam',
        }, # end entity 10032
    10033: {
        'type': 'model',
        'name': 'copy of <unnamed> (2)',
        'comment': '',
        'parentEntId': 10037,
        'pos': Point3(3.5, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'collisionsOnly': 0,
        'flattenType': 'light',
        'goonHatType': 'none',
        'loadType': 'loadModelCopy',
        'modelPath': 'phase_11/models/lawbotHQ/LB_filing_cabA.bam',
        }, # end entity 10033
    10034: {
        'type': 'model',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10035,
        'pos': Point3(-2, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'collisionsOnly': 0,
        'flattenType': 'light',
        'goonHatType': 'none',
        'loadType': 'loadModelCopy',
        'modelPath': 'phase_11/models/lawbotHQ/LB_pottedplantA.bam',
        }, # end entity 10034
    10036: {
        'type': 'model',
        'name': 'copy of <unnamed>',
        'comment': '',
        'parentEntId': 10035,
        'pos': Point3(-2.6, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'collisionsOnly': 0,
        'flattenType': 'light',
        'goonHatType': 'none',
        'loadType': 'loadModelCopy',
        'modelPath': 'phase_11/models/lawbotHQ/LB_pottedplantA.bam',
        }, # end entity 10036
    10040: {
        'type': 'model',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10039,
        'pos': Point3(14.6642, -1.01767, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': Vec3(1.32128, 1.32128, 1.32128),
        'collisionsOnly': 0,
        'flattenType': 'light',
        'goonHatType': 'none',
        'loadType': 'loadModelCopy',
        'modelPath': 'phase_11/models/lawbotHQ/LB_paper_twist_stacks.bam',
        }, # end entity 10040
    10044: {
        'type': 'model',
        'name': 'copy of <unnamed>',
        'comment': '',
        'parentEntId': 10043,
        'pos': Point3(1.75, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'collisionsOnly': 0,
        'flattenType': 'light',
        'goonHatType': 'none',
        'loadType': 'loadModelCopy',
        'modelPath': 'phase_11/models/lawbotHQ/LB_filing_cabA.bam',
        }, # end entity 10044
    10045: {
        'type': 'model',
        'name': 'copy of <unnamed> (2)',
        'comment': '',
        'parentEntId': 10043,
        'pos': Point3(3.5, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'collisionsOnly': 0,
        'flattenType': 'light',
        'goonHatType': 'none',
        'loadType': 'loadModelCopy',
        'modelPath': 'phase_11/models/lawbotHQ/LB_filing_cabA.bam',
        }, # end entity 10045
    10060: {
        'type': 'model',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10043,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'collisionsOnly': 0,
        'flattenType': 'light',
        'goonHatType': 'none',
        'loadType': 'loadModelCopy',
        'modelPath': 'phase_11/models/lawbotHQ/LB_filing_cabA.bam',
        }, # end entity 10060
    10062: {
        'type': 'model',
        'name': 'copy of <unnamed>',
        'comment': '',
        'parentEntId': 10061,
        'pos': Point3(1.75, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'collisionsOnly': 0,
        'flattenType': 'light',
        'goonHatType': 'none',
        'loadType': 'loadModelCopy',
        'modelPath': 'phase_11/models/lawbotHQ/LB_filing_cabA.bam',
        }, # end entity 10062
    10063: {
        'type': 'model',
        'name': 'copy of <unnamed> (2)',
        'comment': '',
        'parentEntId': 10061,
        'pos': Point3(3.5, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'collisionsOnly': 0,
        'flattenType': 'light',
        'goonHatType': 'none',
        'loadType': 'loadModelCopy',
        'modelPath': 'phase_11/models/lawbotHQ/LB_filing_cabA.bam',
        }, # end entity 10063
    10064: {
        'type': 'model',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10061,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'collisionsOnly': 0,
        'flattenType': 'light',
        'goonHatType': 'none',
        'loadType': 'loadModelCopy',
        'modelPath': 'phase_11/models/lawbotHQ/LB_filing_cabA.bam',
        }, # end entity 10064
    10066: {
        'type': 'model',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10065,
        'pos': Point3(8.93303, 26.855, 0),
        'hpr': Vec3(315, 0, 0),
        'scale': Vec3(1.28721, 1.28721, 1.28721),
        'collisionsOnly': 0,
        'flattenType': 'light',
        'goonHatType': 'none',
        'loadType': 'loadModelCopy',
        'modelPath': 'phase_11/models/lawbotHQ/LB_paper_twist_stacks.bam',
        }, # end entity 10066
    10067: {
        'type': 'model',
        'name': 'copy of <unnamed>',
        'comment': '',
        'parentEntId': 10065,
        'pos': Point3(40.4297, -10.7197, 0),
        'hpr': Vec3(41.1859, 0, 0),
        'scale': Vec3(1.38665, 1.38665, 1.38665),
        'collisionsOnly': 0,
        'flattenType': 'light',
        'goonHatType': 'none',
        'loadType': 'loadModelCopy',
        'modelPath': 'phase_11/models/lawbotHQ/LB_paper_twist_stacks.bam',
        }, # end entity 10067
    # NODEPATH
    10002: {
        'type': 'nodepath',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10000,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10002
    10004: {
        'type': 'nodepath',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10000,
        'pos': Point3(-30, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10004
    10005: {
        'type': 'nodepath',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10003,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10005
    10006: {
        'type': 'nodepath',
        'name': 'copy of <unnamed>',
        'comment': '',
        'parentEntId': 10003,
        'pos': Point3(0, 25, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10006
    10013: {
        'type': 'nodepath',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10011,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10013
    10014: {
        'type': 'nodepath',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10011,
        'pos': Point3(-40, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10014
    10021: {
        'type': 'nodepath',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10019,
        'pos': Point3(0, 10, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10021
    10022: {
        'type': 'nodepath',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10019,
        'pos': Point3(0, -10, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10022
    10023: {
        'type': 'nodepath',
        'name': 'upperFloor',
        'comment': '',
        'parentEntId': 0,
        'pos': Point3(0, 60, 10.6166),
        'hpr': Vec3(0, 0, 0),
        'scale': Vec3(1, 1, 1),
        }, # end entity 10023
    10029: {
        'type': 'nodepath',
        'name': 'props',
        'comment': '',
        'parentEntId': 0,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10029
    10030: {
        'type': 'nodepath',
        'name': 'leftWall',
        'comment': '',
        'parentEntId': 10029,
        'pos': Point3(0, -43.0808, 0),
        'hpr': Point3(180, 0, 0),
        'scale': Vec3(2.5, 2.5, 2.5),
        }, # end entity 10030
    10035: {
        'type': 'nodepath',
        'name': 'plants',
        'comment': '',
        'parentEntId': 10030,
        'pos': Point3(0, -0.9, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': Vec3(5, 5, 5),
        }, # end entity 10035
    10037: {
        'type': 'nodepath',
        'name': 'filingCabinets',
        'comment': '',
        'parentEntId': 10030,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': Vec3(1.4, 1.4, 1.4),
        }, # end entity 10037
    10039: {
        'type': 'nodepath',
        'name': 'paperStacks',
        'comment': '',
        'parentEntId': 10030,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10039
    10042: {
        'type': 'nodepath',
        'name': 'props',
        'comment': '',
        'parentEntId': 10023,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10042
    10043: {
        'type': 'nodepath',
        'name': 'filingCabinets',
        'comment': '',
        'parentEntId': 10042,
        'pos': Point3(-40.2501, 9.25953, 0),
        'hpr': Vec3(41.5, 0, 0),
        'scale': Vec3(1.4, 1.4, 1.4),
        }, # end entity 10043
    10048: {
        'type': 'nodepath',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10046,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10048
    10049: {
        'type': 'nodepath',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10046,
        'pos': Point3(0, 10, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10049
    10050: {
        'type': 'nodepath',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10046,
        'pos': Point3(10, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10050
    10053: {
        'type': 'nodepath',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10051,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10053
    10054: {
        'type': 'nodepath',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10051,
        'pos': Point3(0, 10, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10054
    10055: {
        'type': 'nodepath',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10051,
        'pos': Point3(10, 15, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10055
    10058: {
        'type': 'nodepath',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10056,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10058
    10059: {
        'type': 'nodepath',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10056,
        'pos': Point3(20, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10059
    10061: {
        'type': 'nodepath',
        'name': 'filingCabinets',
        'comment': '',
        'parentEntId': 10042,
        'pos': Point3(-29.6959, 18.2379, 0),
        'hpr': Point3(41.5, 0, 0),
        'scale': Vec3(1.4, 1.4, 1.4),
        }, # end entity 10061
    10065: {
        'type': 'nodepath',
        'name': 'paperStacks',
        'comment': '',
        'parentEntId': 10042,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 10065
    100021: {
        'type': 'nodepath',
        'name': 'gauntlet',
        'comment': '',
        'parentEntId': 0,
        'pos': Point3(30, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        }, # end entity 100021
    # PATHMASTER
    10000: {
        'type': 'pathMaster',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 100021,
        'pos': Point3(10, 35, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'pathIndex': 0,
        'pathScale': 1.0,
        'pathTarget0': 10002,
        'pathTarget1': 10004,
        'pathTarget2': 0,
        'pathTarget3': 0,
        'pathTarget4': 0,
        'pathTarget5': 0,
        'pathTarget6': 0,
        'pathTarget7': 0,
        }, # end entity 10000
    10003: {
        'type': 'pathMaster',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 100021,
        'pos': Point3(0, -7, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': Vec3(1, 1, 1),
        'pathIndex': 0,
        'pathScale': 1.0,
        'pathTarget0': 10005,
        'pathTarget1': 10006,
        'pathTarget2': 0,
        'pathTarget3': 0,
        'pathTarget4': 0,
        'pathTarget5': 0,
        'pathTarget6': 0,
        'pathTarget7': 0,
        }, # end entity 10003
    10011: {
        'type': 'pathMaster',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 100021,
        'pos': Point3(0, -35, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': Vec3(1, 1, 1),
        'pathIndex': 0,
        'pathScale': 1.0,
        'pathTarget0': 10013,
        'pathTarget1': 10014,
        'pathTarget2': 0,
        'pathTarget3': 0,
        'pathTarget4': 0,
        'pathTarget5': 0,
        'pathTarget6': 0,
        'pathTarget7': 0,
        }, # end entity 10011
    10019: {
        'type': 'pathMaster',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 100021,
        'pos': Point3(-90, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'pathIndex': 0,
        'pathScale': 1.0,
        'pathTarget0': 10021,
        'pathTarget1': 10022,
        'pathTarget2': 0,
        'pathTarget3': 0,
        'pathTarget4': 0,
        'pathTarget5': 0,
        'pathTarget6': 0,
        'pathTarget7': 0,
        }, # end entity 10019
    10046: {
        'type': 'pathMaster',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 100021,
        'pos': Point3(-30, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'pathIndex': 0,
        'pathScale': 1.0,
        'pathTarget0': 10048,
        'pathTarget1': 10049,
        'pathTarget2': 10050,
        'pathTarget3': 0,
        'pathTarget4': 0,
        'pathTarget5': 0,
        'pathTarget6': 0,
        'pathTarget7': 0,
        }, # end entity 10046
    10051: {
        'type': 'pathMaster',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 100021,
        'pos': Point3(-60, 20, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'pathIndex': 0,
        'pathScale': 1.0,
        'pathTarget0': 10053,
        'pathTarget1': 10054,
        'pathTarget2': 10055,
        'pathTarget3': 0,
        'pathTarget4': 0,
        'pathTarget5': 0,
        'pathTarget6': 0,
        'pathTarget7': 0,
        }, # end entity 10051
    10056: {
        'type': 'pathMaster',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 100021,
        'pos': Point3(-80, -20, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'pathIndex': 0,
        'pathScale': 1.0,
        'pathTarget0': 10058,
        'pathTarget1': 10059,
        'pathTarget2': 0,
        'pathTarget3': 0,
        'pathTarget4': 0,
        'pathTarget5': 0,
        'pathTarget6': 0,
        'pathTarget7': 0,
        }, # end entity 10056
    # RENDERING
    10009: {
        'type': 'rendering',
        'name': 'farCornerGoon',
        'comment': '',
        'parentEntId': 10029,
        'pos': Point3(-60.62, -37.7557, 0),
        'hpr': Vec3(330, 0, 0),
        'scale': Vec3(1, 1, 1),
        'blending': 'Alpha',
        'colorA': 1.0,
        'colorB': 0.20000000000000001,
        'colorG': 0.20000000000000001,
        'colorR': 0.5,
        'fogOn': 0,
        'renderBin': 'transparent',
        }, # end entity 10009
    10016: {
        'type': 'rendering',
        'name': 'nearCornerGoon',
        'comment': '',
        'parentEntId': 10029,
        'pos': Point3(60, -37.76, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'blending': 'Alpha',
        'colorA': 1.0,
        'colorB': 0.20000000000000001,
        'colorG': 0.20000000000000001,
        'colorR': 0.5,
        'fogOn': 0,
        'renderBin': 'transparent',
        }, # end entity 10016
    10025: {
        'type': 'rendering',
        'name': '<unnamed>',
        'comment': '',
        'parentEntId': 10023,
        'pos': Point3(0, 0, 0),
        'hpr': Vec3(0, 0, 0),
        'scale': 1,
        'blending': 'Alpha',
        'colorA': 1.0,
        'colorB': 0.20000000000000001,
        'colorG': 0.20000000000000001,
        'colorR': 0.5,
        'fogOn': 0,
        'renderBin': 'transparent',
        }, # end entity 10025
    }

Scenario0 = {
    }

levelSpec = {
    'globalEntities': GlobalEntities,
    'scenarios': [
        Scenario0,
        ],
    }
